### ISSUE TITLE
Decompilation errors when decompiling

### ISSUE THREAD

**Issue by BrandonDusseau** [mettaur/8XD#8]
See attached file for reference.
[GRD.zip](https://github.com/mettaur/8XD/files/664931/GRD.zip)

**Comment by mettaur** [comment]
Yeah it's getting the file content right, actually, but there's other bytes it's not getting right. 😞

**Comment by mettaur** [comment]
I used `switch(buffer[i++])` instead of `++i` which used the current element before moving onto the next. That's the source of all the issues.
